@startuml
left to right direction
actor 管理職 as m
actor 従業員 as e

rectangle 勤怠管理システム{
'   管理職
    m --> (部下の月毎の勤務実績を確認する)
    note right of (部下の月毎の勤務実績を確認する): 変更のあった勤務実績を視認しやすくしたい
    m --> (部下の勤務状況を確認する)

'   従業員
    e --> (出勤を押す)
    e --> (退勤を押す)
    e --> (月毎に勤務実績を確認する)
    note right of (月毎に勤務実績を確認する): 残業時間や、実労働時間、深夜時間等
    e --> (特定の日の勤務実績を変更する)
}
@enduml
