@startuml
left to right direction
actor 管理職 as m
actor 従業員 as e

rectangle 勤怠管理システム{
'   管理職
    m --> (部下の月毎の勤務実績を確認する)
    note right of (部下の月毎の勤務実績を確認する): 変更のあった勤務実績を視認しやすくしたい

    m --> (部下の勤務状況を確認する)

    usecase (部下全体の有給消化率を確認する) #d3d3d3
    m --> (部下全体の有給消化率を確認する)
    usecase (部下の申請を承認する) #d3d3d3
    usecase (部下の申請を却下する) #d3d3d3
    m --> (部下の申請を承認する)
    m --> (部下の申請を却下する)
    usecase (通知を確認する) #d3d3d3
    m --> (通知を確認する)
        (通知を確認する) <|-- (残業が多い部下がいた場合)
        (通知を確認する) <|-- (有給消化率の低い部下がいた場合)
        (通知を確認する) <|-- (深夜労働時間の多い部下がいた場合)
        (通知を確認する) <|-- (申請がきた場合)
'   従業員
    e --> (出勤する)
    e --> (退勤する)
    e --> (月毎に勤務実績を確認する)
    note right of (月毎に勤務実績を確認する): 残業時間や、実労働時間、深夜時間等
    e --> (特定の日の勤務実績を変更する)

    usecase (申請する) #d3d3d3
    e --> (申請する)
        (申請する) <|-- (休暇申請する)
        (申請する) <|-- (休日出勤申請する)
    usecase (申請のステータスを確認する) #d3d3d3
    e --> (申請のステータスを確認する)
    usecase (自分の有給消化率を確認する) #d3d3d3
    e --> (自分の有給消化率を確認する)
}
@enduml