@startuml
' 一旦申請業務は落とす。
actor 経営者
actor 管理職
actor 従業員

card 所属
card 部署

card 勤務実績一覧
    card 勤務実績
        card 勤務状況
            card 出勤中
            card 退勤中
        card 労働時間
            card 勤務時間
            card 残業時間
            card 深夜労働時間
            card 実労働時間
勤務実績一覧 o-- 勤務実績
勤務実績 o-- 勤務状況
勤務状況 <|-- 出勤中
勤務状況 <|-- 退勤中
勤務実績 o-- 労働時間
労働時間 o-- 実労働時間
労働時間 o-- 残業時間
労働時間 o-- 深夜労働時間
労働時間 o-- 勤務時間
@enduml