@startuml
' 管理職のユースケース記述を書いた後
actor A管理職
actor A従業員

card 勤務既定
card 勤務禁止時間
勤務既定 o-- 勤務禁止時間

card 通知一覧
    card 通知
        card タイプ
            card アラート
            card 情報
通知一覧 o-- 通知
通知 o-- タイプ
タイプ <|-- アラート
タイプ <|-- 情報

' model
card 出勤簿
    card 所定労働日数
    card 実働日数
    card 勤務実績
        card 日付
        card 出退勤情報
            card 出勤時間
            card 退勤時間
        card 勤務状況
            card 未出勤
            card 出勤中
            card 退勤中
            card 欠勤
        card 労働時間
            card 勤務時間
            card 時間外労働時間
            card 休憩時間
            card 深夜労働時間
            card 実労働時間
'relation
出勤簿 o-- 所定労働日数
出勤簿 o-- 実働日数
出勤簿 o-- 勤務実績
    勤務実績 o-- 日付
    勤務実績 o-- 出退勤情報
        出退勤情報 o-- 出勤時間
        出退勤情報 o-- 退勤時間

    勤務実績 o-- 勤務状況
        勤務状況 <|-- 未出勤
        勤務状況 <|-- 出勤中
        勤務状況 <|-- 退勤中
        勤務状況 <|-- 欠勤
    勤務実績 o-up- 労働時間
        労働時間 o-- 実労働時間
        労働時間 o-- 時間外労働時間
        労働時間 o-up- 休憩時間
        労働時間 o-up- 深夜労働時間
        労働時間 o-up- 勤務時間


' model
card アカウント一覧
    card アカウント
'        card 従業員ID
        card 所属部署
    card 権限
        card 管理者権限
        card ユーザー権限
'relation
アカウント一覧 o-- アカウント
'    アカウント o-- 従業員ID
    アカウント o-- 所属部署
    アカウント o-- 通知一覧
    アカウント o-- 出勤簿
    アカウント o-- 権限
        権限 <|-- 管理者権限
        権限 <|-- ユーザー権限

A従業員 o-- アカウント
A管理職 o-- アカウント
@enduml