@startuml
actor 経営者
actor 管理職
actor 従業員

card 所属
card 部署

card 通知一覧
    card 通知
        card タイプ
            card alert
            card info
通知一覧 o-- 通知
通知 o-- タイプ
タイプ <|-- alert
タイプ <|-- info

card 勤務実績一覧
    card 勤務実績
        card 出退勤情報
            card 出勤中
            card 退勤中
        card 労働時間
            card 勤務時間
            card 残業時間
            card 深夜労働時間
            card 実労働時間
勤務実績一覧 o-- 勤務実績
勤務実績 o-- 出退勤情報
出退勤情報 <|-- 出勤中
出退勤情報 <|-- 退勤中
勤務実績 o-- 労働時間
労働時間 o-- 実労働時間
労働時間 o-- 残業時間
労働時間 o-- 深夜労働時間
労働時間 o-- 勤務時間

card 休暇
        card 夏季休暇
        card 有給
            card 消化率
            card 残日数

休暇 <|-- 夏季休暇
休暇 <|-- 有給
有給 o-- 消化率
有給 o-- 残日数

card 申請
    card 休暇取得申請
        card 休暇理由
    card 休日出勤申請
        card 出勤理由
    card ステータス
        card 申請中
        card 承認
        card 却下
    card 申請情報
        card 希望日
        card 申請日
        card 理由
申請 <|-- 休暇取得申請
休暇取得申請 o-- 休暇
    note left of 休暇: あくまで集約は別？
申請 <|-- 休日出勤申請
申請 o-- 申請情報
    申請情報 o-- ステータス
        ステータス <|-- 申請中
        ステータス <|-- 承認
        ステータス <|-- 却下
    申請情報 o-- 希望日
    申請情報 o-- 申請日
    申請情報 o-- 理由
        理由 <|-- 休暇理由
        理由 <|-- 出勤理由
    note top of 申請情報: 詳細やコメントなどを持つ
@enduml