@startuml
' 従業員のユースケース記述を書いた後
actor A経営者
actor A管理職
actor A従業員

card 従業員一覧
card 従業員

card 出勤簿
    card 従業員情報
        card 従業員ID
        card 所属部署
    card 所定労働日数
    card 実働日数
    card 勤務実績
    note top of 勤務実績: 当日の勤務実績をさす
        card 日付
        card 出退勤情報
            card 出勤時間
            card 退勤時間
        card 勤務状況
            card 未出勤
            card 出勤中
            card 退勤中
            card 欠勤
        card 労働時間
            card 勤務時間
            card 時間外労働時間
            card 休憩時間
            card 深夜労働時間
            card 実労働時間
A従業員 o--出勤簿
出勤簿 o-- 従業員情報
    従業員情報 o-- 従業員ID
    従業員情報 o-- 所属部署
出勤簿 o-- 所定労働日数
出勤簿 o-- 実働日数
出勤簿 o-- 勤務実績

    勤務実績 o-- 日付
    勤務実績 o-- 出退勤情報
        出退勤情報 o-- 出勤時間
        出退勤情報 o-- 退勤時間

    勤務実績 o-- 勤務状況
        勤務状況 <|-- 未出勤
        勤務状況 <|-- 出勤中
        勤務状況 <|-- 退勤中
        勤務状況 <|-- 欠勤
    勤務実績 o-- 労働時間
        労働時間 o-- 実労働時間
        労働時間 o-- 時間外労働時間
        労働時間 o-- 休憩時間
        労働時間 o-- 深夜労働時間
        労働時間 o-- 勤務時間

note bottom of 出勤時間
    勤務禁止時間は出勤アラートが出る
end note
note bottom of 勤務時間
    週35時間超過している場合、アラート
end note
note bottom of 時間外労働時間
    月4時間超過している場合、アラート
end note

note left of 出退勤情報
    - 出勤時間が存在しない場合、退勤時間の値は持てない
    - 出勤時間が既に存在する場合、新たに出勤時間は持てない
    - 常に (出勤時間の個数)X>=(退勤時間の個数)Yである事
end note
@enduml