@startuml
actor 管理職
boundary 従業員一覧画面
control 従業員一覧画面を表示#white

entity 出勤簿 #e0ffff
entity 従業員 #e0ffff
entity 権限#e0ffff

control 従業員をクリック
control 従業員の出勤簿を表示する

control ログインしているか
control 権限があるか
    control 権限がありませんのエラー表示
control ログイン画面にリダイレクト

管理職 --> 従業員一覧画面を表示
従業員一覧画面を表示 --> 従業員一覧画面

従業員一覧画面 --> 従業員をクリック
従業員をクリック--従業員

従業員をクリック --> ログインしているか
ログインしているか--ログイン画面にリダイレクト:いいえ
ログインしているか --> 権限があるか: はい
権限があるか--権限がありませんのエラー表示:いいえ
権限があるか --> 従業員の出勤簿を表示する: はい
権限があるか--権限
従業員の出勤簿を表示する--出勤簿
@enduml