@startuml
'Actor
Actor 従業員
'Boundary
boundary 打刻画面

'Entity
entity 勤務禁止時間 #e0ffff
entity 通知 #e0ffff
entity 時間外労働時間 #e0ffff
entity 勤務状況 #e0ffff
entity 出退勤情報 #e0ffff
entity 実労働時間 #e0ffff

'Control
'view
control 打刻画面を表示する #white

'if
control 勤務禁止時間かを確認 #pink
control 今週の実労働時間が35時間を超過していないかを確認 #pink
control 今月の時間外労働時間が40時間を超過していないかを確認 #pink
control 出勤中か確認 #pink

'method
control 管理職にアラート通知 #green
control 既に出勤中ですのダイアグラムを出す #green
control 出退勤情報を更新 #green

従業員 -> 打刻画面
打刻画面を表示する -- 打刻画面
打刻画面 -- 勤務禁止時間かを確認: ボタンをクリック

管理職にアラート通知 - 通知

勤務禁止時間かを確認 -- 管理職にアラート通知: はい
勤務禁止時間かを確認 --> 今週の実労働時間が35時間を超過していないかを確認: いいえ
勤務禁止時間かを確認 - 勤務禁止時間

今週の実労働時間が35時間を超過していないかを確認 -- 管理職にアラート通知: はい
今週の実労働時間が35時間を超過していないかを確認 --> 今月の時間外労働時間が40時間を超過していないかを確認: いいえ
今週の実労働時間が35時間を超過していないかを確認 - 実労働時間

今月の時間外労働時間が40時間を超過していないかを確認 -- 管理職にアラート通知: はい
今月の時間外労働時間が40時間を超過していないかを確認 --> 出勤中か確認: いいえ
今月の時間外労働時間が40時間を超過していないかを確認 - 時間外労働時間

出勤中か確認 --> 既に出勤中ですのダイアグラムを出す: はい
出勤中か確認 --> 出退勤情報を更新: いいえ
出勤中か確認 - 勤務状況

出退勤情報を更新 --> 打刻画面を表示する
出退勤情報を更新--出退勤情報


@enduml
