@startuml
actor 従業員
boundary 出勤簿画面を表示

entity 出勤簿 #e0ffff
entity セッション情報 #e0ffff

control 出勤簿を表示する #white

control 指定月期間を選択する#green
control 無垢なリクエスト#green
control ログイン画面にリダイレクト#green

control 入力が正しいか #pink
control ログイン中のアカウントの出勤簿か #pink


従業員 --> 出勤簿を表示する
出勤簿を表示する -- 出勤簿
出勤簿を表示する --> 出勤簿画面を表示

出勤簿画面を表示 --> 指定月期間を選択する
指定月期間を選択する --> 入力が正しいか
入力が正しいか -- 無垢なリクエスト: いいえ
入力が正しいか --> ログイン中のアカウントの出勤簿か: はい
ログイン中のアカウントの出勤簿か--ログイン画面にリダイレクト:いいえ
ログイン中のアカウントの出勤簿か --> 出勤簿画面を表示:はい
ログイン中のアカウントの出勤簿か--セッション情報
@enduml